LiquorOnline/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LiquorOnline.Data;
using LiquorOnline.Models;

using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace LiquorOnline.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly LiquorOnlineContext _context;

        public ProductsController(LiquorOnlineContext context, IWebHostEnvironment webHost)
        {
            _context = context;
            webHostEnvironment = webHost;
        }

        // GET: Products
        public async Task<IActionResult> Index(string searchString, int pg=1)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'product'  is null.");
            }

            var products = from m in _context.Product
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.Productname!.Contains(searchString));
            }

            const int pageSize = 12;
            if (pg > 1)
            {
                pg = 1;
            }

            int recsCount = products.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = products.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            //return View(await products.ToListAsync());
            return View(data);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        private string? UploadedFile(Product product)
        {
            string? uniqueFileName = null;

            if (product.ProductImage != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() +"_" + product.ProductImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    product.ProductImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]







        //DHJFHJGJH
        public async Task<IActionResult> Create([Bind("ProductId,Productname,Brand,Description,Deliver,Quantity,ProductImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                string? uniqueFileName = UploadedFile(product);
                product.ImageUrl = uniqueFileName;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            product.ImageUrl = Url.Content("../images/" + product.ImageUrl);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Productname,Brand,Description,Deliver,Quantity,ProductImage")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string? uniqueFileName = UploadedFile(product);
                    product.ImageUrl = uniqueFileName;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'LiquorOnlineContext.Product'  is null.");
            }
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.Product?.Any(e => e.ProductId == id)).GetValueOrDefault();
        }
    }
}

LiquorOnline/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LiquorOnline.Data;
using LiquorOnline.Models;

namespace LiquorOnline.Controllers
{
    public class UsersController : Controller
    {
        private readonly LiquorOnlineContext _context;

        public UsersController(LiquorOnlineContext context)
        {
            _context = context;
        }

        // GET: Users
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string searchString, int pg=1)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'user'  is null.");
            }

            var users = from m in _context.Users
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => s.Firstname!.Contains(searchString) || s.Lastname!.Contains(searchString));
            }

            const int pageSize = 12;
            if (pg > 1)
            {
                pg = 1;
            }

            int recsCount = users.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = users.Skip(recSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            //return View(await users.ToListAsync());
            return View(data);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,NIC,Firstname,Lastname,Username,Email,Password,Address,ContactNo")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Role = "User";
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,NIC,Firstname,Lastname,Username,Email,Password,Address,ContactNo,Role")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'LiquorOnlineContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.Users?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

LiquorOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LiquorOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LiquorOnline.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
</head>
<body class="mb-0 " >
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <a class="navbar-brand p-3 text-dark" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/1w.png" width="100px" height="100px"></a>
                <!-- Toggle button -->
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarRightAlignExample"
                        aria-controls="navbarNavAltMarkup"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarRightAlignExample" >
                    <!-- Left links -->
                    <ul class="navbar-nav mb-3 mb-lg-0  ">
                        <li class="nav-item">
                            <style>
                                .navbar-nav .nav-link {
                                    font-size: 20px;/* Adjust the value as needed to increase the font size */
                                    margin-right: 50px;
                                }
                            </style>
                            <a class="nav-link text-light " asp-area="" asp-controller="Home" asp-action="Index"  >Liquor Online </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link  text-light " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link  text-light " asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link  text-light " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                       
                        <!-- Navbar dropdown -->
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown" >
                                <a class="nav-link dropdown-toggle  text-light"
                                   href="#"
                                   role="button"
                                   data-bs-toggle="dropdown"
                                   aria-expanded="false"
                                   >
                                    DashBoard
                                </a>
                                <!-- Dropdown menu -->
                                <ul class="dropdown-menu bg-dark">
                                    <li>
                                        <a class="dropdown-item bg-white text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item bg-white text-dark" asp-area="" asp-controller="Users" asp-action="Index">Customers</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link  text-light" href="#">My Profile</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link  text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link  text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  text-light" asp-area="" asp-controller="Users" asp-action="Create">Register</a>
                            </li>
                        }
                        <li class="nav-item cart-item">
                            <a class="nav-link text-light " asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                        </li>
                        <ul  class="navbar-nav">
                            <li class="nav-item">
                                
                            <li  class="nav-item cart-item">
                                <a class="nav-link text-light " asp-area="" asp-controller="Home" asp-action="Cart">Cart</a>
                            </li>
                        </ul>
                        




                    </ul>
                    <!-- Left links -->
                </div>
                <!-- Collapsible wrapper -->
            </div>
            <!-- Container wrapper -->
        </nav>
    </header>
    <div class="container   " padding-top="40px" ;>
        <main role="main"  class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="text-center text-lg-start bg-dark text-muted">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-3 border-bottom">
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
                <span>Get connected with us on social networks:</span>
            </div>
            <!-- Left -->
            <!-- Right -->
            <div>
                <a href="https://www.facebook.com/" class="me-4 link-secondary">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="https://twitter.com/" class="me-4 link-secondary">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="https://google.com/" class="me-4 link-secondary">
                    <i class="fab fa-google"></i>
                </a>
                <a href="https://instagram.com/" class="me-4 link-secondary">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="https://linkedin.com/" class="me-4 link-secondary">
                    <i class="fab fa-linkedin"></i>
                </a>
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->
        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5 mb-0">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3 text-secondary"></i>Online Liquor
                        </h6>
                      
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Products
                        </h6>
                        <p>
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="text-reset">Tools</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Contact Us</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Cart</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                        <p><i class="fas fa-home me-3 text-secondary"></i> Panchikawaththa, Colombo 07, Sri Lanka.</p>
                        <p>
                            <i class="fas fa-envelope me-3 text-secondary"></i>
                            liquoronline@gmail.com
                        </p>
                        <p><i class="fas fa-phone me-3 text-secondary"></i> + 94 222 333 44</p>
                        <p><i class="fas fa-print me-3 text-secondary"></i> + 94 333 444 55</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.025);">
            © 2023 Copyright:
            <a class="text-reset fw-bold" a asp-area="" asp-controller="Home" asp-action="Index">LiquorOnline.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>